### ISSUE TITLE
用这个项目能找到工作吗？

### ISSUE THREAD

**Issue by chuck-0123** [578223592/rpc1#1]

**Comment by 578223592** [comment]
深圳申请外卖可以不用排队了

**Comment by chuck-0123** [comment]
八嘎


曹钰坤
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "578223592/rpc1"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月10日(星期一) 下午4:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [578223592/rpc1] 用这个项目能找到工作吗？ (Issue #1)





 
深圳申请外卖可以不用排队了
